# Generated by Django 5.0.6 on 2024-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=250)),
                ('tesseract_text', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[('0', 'Processing'), ('1', 'Complete'), ('2', 'Failed')], default=0)),
                ('error', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
