# Generated by Django 5.0.6 on 2024-05-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateExecutionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('generation_type', models.CharField(choices=[('MCQ', 'Multiple Choice Questions'), ('FRQ', 'Free Response Questions')], max_length=3)),
                ('file_model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.filemodel')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestionsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(null=True)),
                ('question_text_context', models.TextField(null=True)),
                ('answer_text', models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('generate_execution_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.generateexecutionmodel')),
            ],
        ),
    ]
